# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'confirmationDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConfirmationDialog(object):
    def setupUi(self, Dialog, msg):
        Dialog.setObjectName("Dialog")
        Dialog.resize(273, 116)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.msg = QtWidgets.QLabel(Dialog)
        self.msg.setAlignment(QtCore.Qt.AlignCenter)
        self.msg.setObjectName("msg")
        self.gridLayout.addWidget(self.msg, 0, 0, 1, 1)
        self.btnOk = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOk.sizePolicy().hasHeightForWidth())
        self.btnOk.setSizePolicy(sizePolicy)
        self.btnOk.setObjectName("btnOk")
        self.gridLayout.addWidget(self.btnOk, 1, 0, 1, 1)

        self.retranslateUi(Dialog, msg)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog, msg):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Confirmation"))
        self.msg.setText(_translate("Dialog", msg))
        self.btnOk.setText(_translate("Dialog", "Ok"))
